name: Node.js CI

on: push

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [12.x]
    
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: install node dependencies
      working-directory: ./src
      run: npm install

    - name: check eslint
      working-directory: ./src
      run: npm lint

    - name: mocha testing
      working-directory: ./src
      run: npm test

      env:
        CI: true
        DBXACCESSTOKEN: ${{secrets.DBXACCESSTOKEN}}
